### ISSUE TITLE
There is no UserStates module in the project.

### ISSUE THREAD

**Issue by alex-liupeng** [tonydangblog/liveview-svelte-pwa#1]
↳ :elixir_compiler_1.__FILE__/1, at: priv/repo/seeds.exs:18
** (Protocol.UndefinedError) protocol Ecto.Queryable not implemented for LiveViewSvelteOfflineDemo.UserStates.UserState of type Atom, the given module does not exist. This protocol is implemented for the following type(s): Atom, BitString, Ecto.Query, Ecto.SubQuery, Tuple
    (ecto 3.11.0) lib/ecto/queryable.ex:41: Ecto.Queryable.Atom.to_query/1
    (ecto 3.11.0) lib/ecto/repo/queryable.ex:184: Ecto.Repo.Queryable.delete_all/3
    priv/repo/seeds.exs:19: (file)
    (elixir 1.16.1) lib/code.ex:1485: Code.require_file/2
    (mix 1.16.1) lib/mix/tasks/run.ex:146: Mix.Tasks.Run.run/5
    (mix 1.16.1) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix 1.16.1) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.1) lib/mix/task.ex:544: Mix.Task.run_alias/6
    (mix 1.16.1) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /home/alex/.asdf/installs/elixir/1.16.1-otp-26/bin/mix:2: (file)

**Comment by thisistonydang** [comment]
Hi! Thanks for the catch. This seed script is outdated. There used to be a `UserStates` module in a previous version of the app when I had a hand-rolled CRDT implementation. However, after I switched to using Yjs as my CRDT library, this module was no longer used and I no longer had a seed script. 

I went ahead and deleted the seed script so that there isn't any confusion!
